### ISSUE TITLE
Add default max-width for images

### ISSUE THREAD

**Issue by erwstout** [factor1/prelude-wp#53]
Would be nice to have a css property containing images to their parents. Is a default property in Foundation but not Ginger, so adding it to `global.scss` would be great. 

```scss
img{
  max-width: 100%;
  height: auto;
}
```
