### ISSUE TITLE
Add Yelp to social menu

### ISSUE THREAD

**Issue by erwstout** [factor1/prelude-wp#96]
Add yelp icon to social media css.

**Comment by erwstout** [comment]
```scss
a[href*="yelp.com"]::before {
    content: '\f1e9';
  }
```
